apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluent-bit
  namespace: apm
  labels:
    app: fluent-bit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fluent-bit
  template:
    metadata:
      labels:
        app: fluent-bit
    spec:
      imagePullSecrets:
        - name: __PULL_SECRET_NAME__
      containers:
        - name: fluent-bit
          image: __IMAGE_REPO__/fluent-bit:latest
          imagePullPolicy: IfNotPresent
          args:
            - -c
            - /fluent-bit/etc/fluent-bit.yaml
          ports:
            - containerPort: 9882
              name: prom-rw
              protocol: TCP
          volumeMounts:
            - name: fluent-bit-config
              mountPath: /fluent-bit/etc
            - name: fluent-bit-storage
              mountPath: /fluent-bit-storage
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "500m"
      volumes:
        - name: fluent-bit-config
          configMap:
            name: fluent-bit-config
        - name: fluent-bit-storage
          emptyDir: {}
